source 'https://rubygems.org'

gem 'rails', '5.1.3'

gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '>= 4.0.0'
gem 'therubyracer',  platforms: :ruby

gem 'sprockets', '>= 3.0.0'
gem 'ngannotate-rails', path: File.expand_path('../../..', __FILE__), require: true

gem 'rspec-rails'
gem 'rack-test'

# various misc useful utilities
gem 'pry-rails'
gem 'awesome_print'
gem 'oj'
gem 'hashie'
gem 'pry-byebug'
