source 'https://rubygems.org'

gem 'rails', '~> 4.2.0'

gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'therubyracer',  platforms: :ruby

gem 'sprockets', '3.0.0.beta.8'
gem 'ngannotate-rails', path: File.expand_path('../../..', __FILE__), require: true
